### ISSUE TITLE
TDS crasha ao comparar fontes via Source Control do VsCode

### ISSUE THREAD

**Issue by gtrabach** [totvs/tds-vscode#1142]
**Describe the bug**
Após a última atualização do TDS (versão 1.3.21), ao alterar qualquer fonte e tentar visualizar suas alterações através do menu Source Control, o TDS irá crashar e entrará em um looping de erros até ser desabilitado pelo VsCode.

**To Reproduce**
1. Utilize a versão 1.3.21 da extensão.
2. Usando o controle de versão, altere qualquer fonte do seu projeto.
3. Utilizando o menu Source Control, compare versões entre o fonte anterior e o novo.
4. Observe as mensagens geradas no console.

**Expected behavior**
Em versões anteriores era possível comparar fontes normalmente sem exibição dos erros do TDS.

**Desktop (please complete the following information):**
Windows 11 Pro 22H2 64-bits
[evidencias.zip](https://github.com/totvs/tds-vscode/files/12464269/evidencias.zip)

**Appserver (please complete the following information):**
AppServer 20.3.1.12
Windows Server 2012 R2

**Comment by lwtnb-wrk** [comment]
@gtrabach Ao abrir esse fonte (elson.pouiapp.elfatm97.service.tlpp) em questao, sem ser no comparador do Source Control o problema não ocorre? Parece ser algo especifico desse fonte que esta causado o crash, favor ver em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs gerados para analise.
Se possivel nos envie tambem esse fonte (elson.pouiapp.elfatm97.service.tlpp)
Outro teste que voce pode tentar fazer seria abrir as preferencias (CTRL + ,) e procurar por "Linter" em TOTVS e experimentar desabilita-lo desmarcando o checkbox (reinicie o tds-vscode).

**Comment by gtrabach** [comment]
@lwtnb-wrk Fiz alguns testes aqui e percebi que esse erro só ocorre em fontes .tlpp, independente do fonte. Ao abrir o arquivo normalmente (sem ser pelo source control) o erro não é exibido. Fontes .prw também não exibem o erro.

Desabilitei o Linter conforme sugerido mas o problema persistiu.

Segue mensagem completa:
[Info  - 09:35:13] Initializing Language Server.
[Info  - 09:35:19] Language Server initialized.
[Info  - 09:35:19] Developer Support Subsystem initialized.
[Info  - 09:35:19] Starting reconnection to the server 'PRODUCAO'
[Info  - 09:35:20] Secure authenticating...
[Info  - 09:35:26] User authenticated successfully.
[Info  - 09:35:26] Reconnection to the server 'PRODUCAO' finished.
[Info  - 09:35:32] Connection to server got closed. Server will restart.
[Error - 09:35:32] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\giordano.xavier\.vscode\extensions\totvs.tds-vscode-1.3.21\out\extension.js:56:2821)
	at Object.dispose (c:\Users\giordano.xavier\.vscode\extensions\totvs.tds-vscode-1.3.21\out\extension.js:61:7996)
	at jp.handleConnectionClosed (c:\Users\giordano.xavier\.vscode\extensions\totvs.tds-vscode-1.3.21\out\extension.js:63:8344)
	at jp.handleConnectionClosed (c:\Users\giordano.xavier\.vscode\extensions\totvs.tds-vscode-1.3.21\out\extension.js:63:34609)
	at r (c:\Users\giordano.xavier\.vscode\extensions\totvs.tds-vscode-1.3.21\out\extension.js:63:8064)
	at A_.invoke (c:\Users\giordano.xavier\.vscode\extensions\totvs.tds-vscode-1.3.21\out\extension.js:27:27637)
	at Al.fire (c:\Users\giordano.xavier\.vscode\extensions\totvs.tds-vscode-1.3.21\out\extension.js:27:28371)
	at At (c:\Users\giordano.xavier\.vscode\extensions\totvs.tds-vscode-1.3.21\out\extension.js:30:12228)
	at A_.invoke (c:\Users\giordano.xavier\.vscode\extensions\totvs.tds-vscode-1.3.21\out\extension.js:27:27637)
	at Al.fire (c:\Users\giordano.xavier\.vscode\extensions\totvs.tds-vscode-1.3.21\out\extension.js:27:28371)
	at gp.fireClose (c:\Users\giordano.xavier\.vscode\extensions\totvs.tds-vscode-1.3.21\out\extension.js:29:1810)
	at Socket.<anonymous> (c:\Users\giordano.xavier\.vscode\extensions\totvs.tds-vscode-1.3.21\out\extension.js:29:2578)
	at Socket.emit (node:events:538:35)
	at Pipe.<anonymous> (node:net:687:12)

Na versão anterior do TDS, pude perceber que não existia esse "Developer Support Subsystem initialized.". Talvez a causa esteja relacionada a essa modificação.

Em anexo fonte para teste e logs.


[logs e fonte.zip](https://github.com/totvs/tds-vscode/files/12464573/logs.e.fonte.zip)

**Comment by lwtnb-wrk** [comment]
@gtrabach Voce forçou alguma atualização no tds-vscode ou instalou outras versões antes? 
Esse "Developer Support Subsystem" é uma coisa nova que vai sair no tds-vscode 2.0.0
Se for o caso, desinstale a extensão, reinicie o VS Code e instale novamente para ver se resolve.

**Comment by gtrabach** [comment]
@lwtnb-wrk Não, a extensão atualizou automaticamente. Só voltei a versão depois que esse erro começou a ocorrer.

Removi a extensão, reiniciei o VSCode e instalei novamente e o erro continua ocorrendo. Novamente a mensagem "Developer Support Subsystem initialized" é exibida.

![image](https://github.com/totvs/tds-vscode/assets/46979335/d01b87c8-7549-4d4a-94af-96b8d2ced33f)

**Comment by lwtnb-wrk** [comment]
@gtrabach Poderia fazer mais um teste então?
Desinstale novamente o v1.3.21 e reinicie o VS Code.
Baixe o vsix 1.3.21 deste link https://github.com/totvs/tds-vscode/releases/tag/v1.3.21
E instale manualmente conforme https://github.com/totvs/tds-vscode/blob/master/docs/install.md
Veja se isso resolve o problema relatado

**Comment by gtrabach** [comment]
@lwtnb-wrk usando o vsix funcionou corretamente! A mensagem "Developer Support Subsystem initialized" não foi mais exibida e a comparação via Source Control não apresentou erros.

**Comment by lwtnb-wrk** [comment]
@gtrabach Grato pelo teste

**Comment by gtrabach** [comment]
@lwtnb-wrk apenas por curiosidade, foi um problema específico na versão expedida pelo marketplace? Devo continuar usando a versão do vsix?

**Comment by lwtnb-wrk** [comment]
@gtrabach Sim, foi isso mesmo, e ja expedimos uma v1.3.22 com a correção, se quiser atualizar ela nao deve mudar em nada em relacao ao vsix instalado manualmente. 
Alias se puder testar ja e nos passar o resultado, ja confirmaria que a ultima versao 1.3.22 esta em ordem enfim.

**Comment by gtrabach** [comment]
@lwtnb-wrk atualizei aqui e funcionou corretamente.
