### ISSUE TITLE
Classe no TL++

### ISSUE THREAD

**Issue by dabraga** [totvs/tds-vscode#1234]
Quando digito Classs e dou um espaço e começo a digitar o nome da class está dando esse erro 
Error: Illegal argument: line must be non-negative
	at p (e:\IDE\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:1029)
	at new f (e:\IDE\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:4802)
	at new a (e:\IDE\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:6333)
	at m (c:\Users\d.braga\.vscode\extensions\totvs.tds-vscode-2.0.7\out\extension.js:56:66068)
	at ge (c:\Users\d.braga\.vscode\extensions\totvs.tds-vscode-2.0.7\out\extension.js:56:73405)
	at o (c:\Users\d.braga\.vscode\extensions\totvs.tds-vscode-2.0.7\out\extension.js:56:48512)
	at Object.fee [as map] (c:\Users\d.braga\.vscode\extensions\totvs.tds-vscode-2.0.7\out\extension.js:56:48598)
	at Object.Vi [as asDocumentSymbols] (c:\Users\d.braga\.vscode\extensions\totvs.tds-vscode-2.0.7\out\extension.js:56:73320)
	at c (c:\Users\d.braga\.vscode\extensions\totvs.tds-vscode-2.0.7\out\extension.js:60:56101)
	at async r.provideDocumentSymbols (e:\IDE\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:90654)
[Error - 10:16:17 AM] Request textDocument/documentSymbol failed.
Error: Illegal argument: line must be non-negative
	at p (e:\IDE\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:1029)
	at new f (e:\IDE\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:4802)
	at new a (e:\IDE\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:6333)
	at m (c:\Users\d.braga\.vscode\extensions\totvs.tds-vscode-2.0.7\out\extension.js:56:66068)
	at ge (c:\Users\d.braga\.vscode\extensions\totvs.tds-vscode-2.0.7\out\extension.js:56:73405)
	at o (c:\Users\d.braga\.vscode\extensions\totvs.tds-vscode-2.0.7\out\extension.js:56:48512)
	at Object.fee [as map] (c:\Users\d.braga\.vscode\extensions\totvs.tds-vscode-2.0.7\out\extension.js:56:48598)
	at Object.Vi [as asDocumentSymbols] (c:\Users\d.braga\.vscode\extensions\totvs.tds-vscode-2.0.7\out\extension.js:56:73320)
	at c (c:\Users\d.braga\.vscode\extensions\totvs.tds-vscode-2.0.7\out\extension.js:60:56101)
	at async r.provideDocumentSymbols (e:\IDE\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:90654)

**Comment by lwtnb-wrk** [comment]
@dabraga Tem um fonte simples que seja fácil reproduzir o erro, para nos passar?
