### ISSUE TITLE
Aplicação de Patch (Apply Patch)

### ISSUE THREAD

**Issue by tiagomalta** [totvs/tds-vscode#573]
Os botões de "APPLY" e "APPLY/CLOSE" não funcionam e não aplicam as atualizações.

![image](https://user-images.githubusercontent.com/66265569/99259968-8c5a4c00-27f9-11eb-8af9-d35c46bbb02d.png)

![image](https://user-images.githubusercontent.com/66265569/99260012-9f6d1c00-27f9-11eb-89b4-d21b26a6711a.png)

![image](https://user-images.githubusercontent.com/66265569/99260047-ad22a180-27f9-11eb-91c9-a49c7bb90a81.png)

Segue a tela.

**Comment by brodao** [comment]
Ola @tiagomalta 

Favor ver [Gerando logs](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs) e anexá-los ao chamado.

No aguardo.

**Comment by tiagomalta** [comment]
[totvsls.log](https://github.com/totvs/tds-vscode/files/5546734/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/5546735/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/5546736/totvsls_out.log)

**Comment by brodao** [comment]
Ola @tiagomalta 

Nesses logs você executou o processo que apresentou erro?

**Comment by tiagomalta** [comment]
ola @brodao ,

Na descrição issue coloquei que os botões não estão funcionando, aparentemente estão sem ação para confirmar a aplicação de patch.

**Comment by lwtnb-wrk** [comment]
@tiagomalta Eu testei aqui e aplicou um patch sem problemas.
A tela "Apply Patch" então permanece aberta e não faz nada ao clicar no "Apply/Close"?

**Comment by tiagomalta** [comment]
@lwtnb-wrk isso mesmo permanece aberta como se o botão estivesse sem ação, fiz o testes se alterar o plugin para a versão 1.0.6 volta a funcionar a aplicação de patch.

**Comment by tiagomalta** [comment]
@brodao @lwtnb-wrk segue a demonstração:

![GIF](https://user-images.githubusercontent.com/66265569/99295198-deb06280-2823-11eb-9330-fc2651a3ae9a.gif)

**Comment by tiagomalta** [comment]
@brodao @lwtnb-wrk utilizando a ferramenta de desenvolvedor dentro do vscode, consegui o log abaixo:

mainThreadExtensionService.ts:65 [[object Object]]Cannot read property 'authorizationToken' of undefined
$onExtensionRuntimeError @ host.ts:10
_doInvokeHandler @ rpcProtocol.ts:365
_invokeHandler @ rpcProtocol.ts:365
_receiveRequest @ rpcProtocol.ts:306
_receiveOneMessage @ rpcProtocol.ts:174
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:584
fire @ ipc.net.ts:431
_receiveMessage @ ipc.net.ts:764
(anonymous) @ ipc.net.ts:624
fire @ event.ts:584
acceptChunk @ ipc.net.ts:174
(anonymous) @ ipc.net.ts:174
t @ ipc.net.ts:900
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'authorizationToken' of undefined
	at Object.<anonymous> (c:\Users\eu_ty\.vscode\extensions\totvs.tds-vscode-1.2.0\out\patch\patchApply.js:76:79)
	at Generator.next (<anonymous>)
	at c:\Users\eu_ty\.vscode\extensions\totvs.tds-vscode-1.2.0\out\patch\patchApply.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\eu_ty\.vscode\extensions\totvs.tds-vscode-1.2.0\out\patch\patchApply.js:4:12)
	at c:\Users\eu_ty\.vscode\extensions\totvs.tds-vscode-1.2.0\out\patch\patchApply.js:60:71
	at l.fire (c:\Users\eu_ty\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
	at t.ExtHostWebviews.$onMessage (c:\Users\eu_ty\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:847:889)
	at g._doInvokeHandler (c:\Users\eu_ty\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:876:926)
	at g._invokeHandler (c:\Users\eu_ty\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:876:618)
	at g._receiveRequest (c:\Users\eu_ty\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:875:252)
	at g._receiveOneMessage (c:\Users\eu_ty\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:874:6)
	at c:\Users\eu_ty\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:872:136
	at l.fire (c:\Users\eu_ty\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
	at v.fire (c:\Users\eu_ty\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:601)
	at c:\Users\eu_ty\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1066:179
	at l.fire (c:\Users\eu_ty\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
	at v.fire (c:\Users\eu_ty\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:601)
	at t.PersistentProtocol._receiveMessage (c:\Users\eu_ty\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:261:629)
	at c:\Users\eu_ty\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:258:708
	at l.fire (c:\Users\eu_ty\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
	at p.acceptChunk (c:\Users\eu_ty\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:989)
	at c:\Users\eu_ty\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:341
	at Socket.t (c:\Users\eu_ty\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:263:276)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
$onExtensionRuntimeError @ host.ts:10
_doInvokeHandler @ rpcProtocol.ts:365
_invokeHandler @ rpcProtocol.ts:365
_receiveRequest @ rpcProtocol.ts:306
_receiveOneMessage @ rpcProtocol.ts:174
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:584
fire @ ipc.net.ts:431
_receiveMessage @ ipc.net.ts:764
(anonymous) @ ipc.net.ts:624
fire @ event.ts:584
acceptChunk @ ipc.net.ts:174
(anonymous) @ ipc.net.ts:174
t @ ipc.net.ts:900
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181

**Comment by lwtnb-wrk** [comment]
@tiagomalta Ah excelente informação. Consegui reproduzir o seu problema.
Já vamos efetuar a correção e até a próxima semana devemos disponibilizar uma atualização.
Grato pelas informações.

**Comment by lwtnb-wrk** [comment]
Geramos um VSIX versão 1.2.1 que está em Pré Release (Draft) em https://github.com/totvs/tds-vscode/releases/tag/untagged-4836c4e75f678708b252
Se quiserem/puderem baixar e instalar manualmente este VSIX para avaliar se o seu problema relatado foi solucionado, favor nos informar se está corrigido ou não para que possamos realizar a liberação oficial.
Para instalar manualmente o VSIX baixem do link acima e na aba de "Extensões" do VS Code clique em "..." e selecione "Install from VSIX" e apontem para o arquivo baixado.

**Comment by adriano-lollybaby** [comment]
Olá,

Estava com o mesmo problema na 1.2.0 (voltei para a versão 1.1.1)

Atualizei para a versão 1.2.1 e o problema continua.

Em ambas as versões, ele gera a mensagem: Insufficient privileges for APPLY_PATCH

Obs: consigo usar outros recursos, como Inspetor de Objetos

Voltei novamente para a 1.1.1

**Comment by sjijrp** [comment]
Para mim a 1.2.1 resolveu o problema, mas o visual code precisa estar atualizado na 1.5.1.1

**Comment by adriano-lollybaby** [comment]
> Para mim a 1.2.1 resolveu o problema, mas o visual code precisa estar atualizado na 1.5.1.1

Estou com essa versão: 1.51.1...

**Comment by xhuntet** [comment]
Boa noite,

Também estou com o mesmo problema.
Segui as orientações e o problema permanece.

**Comment by brodao** [comment]
Senhores,

Favor remover a extensão, reiniciar o TDS-VSCode e instalarem novamente. Verificamos que em determinadas situações, a atualização pode não ocorrer. Ainda não conseguimos identificar o motivo.

A disposição.

**Comment by xhuntet** [comment]
Bom dia Srs.,

Realizei a operação sugerida e tudo permanece como antes, ou seja, a
funcionalidade de aplicação de patch não apresenta qualquer comportamento.

Att.

**Comment by xhuntet** [comment]
Srs.,

Analisando as configurações da extensão, verifiquei que há uma configuração para apresentação de mensagens, que no meu caso, precisava ser ativada, conforme a sequencia de telas abaixo.

![image](https://user-images.githubusercontent.com/26895616/104603338-0fade780-565b-11eb-9030-b22676f4aebe.png)

No meu caso, estava "none" e passei para "all".

![image](https://user-images.githubusercontent.com/26895616/104603534-4683fd80-565b-11eb-8b31-f19185d2dfb0.png)

Em seguida a aplicação de patches passou a apresentar as mensagens referentes ao processo.

![image](https://user-images.githubusercontent.com/26895616/104604073-d0cc6180-565b-11eb-9fac-26ab99a96908.png)

Desse modo, segui as ultimas orientações para atualização, postadas nessa ISSUE e ativei a apresentação de mensagens.

Abs.

**Comment by danielbolognani** [comment]
@xhuntet Verifique o console do appserver, se tiver alguém estiver utilizando o RPO (acessando alguma rotina por exemplo), é exatamente essa mensagem que aparece. Se for um appserver local, ative a chave BuildKillUsers=1 no General do Appserver.ini para matar todas as conexões antes de aplicar o patch.

**Comment by xhuntet** [comment]
Obrigado Daniel!

Na verdade o Patch Apply passou a funcionar com o VSIX que foi postado, mas
como a mensageria do meu IDE estava desabilitada, o comportamento
permanecia igual ao informado na abertura desta ISSUE.

Habilitei as mensagens e pronto, passou a apresentar todo o andamento do
processo de aplicação de patch.

Um abraço!


Em qui., 14 de jan. de 2021 às 12:00, Daniel Otto Bolognani <
notifications@github.com> escreveu:
