### ISSUE TITLE
Conectar nos Servidores

### ISSUE THREAD

**Issue by Miqueiasfer** [totvs/tds-vscode#710]
Bom Dia, nao estou conseguindo conectar no servidores no totvs developer, quando clico em um ambiente retorna o erro abaixo:

[2021-06-23 08:02:26.114] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/miqueias.fernandes/.vscode/extensions/totvs.tds-vscode-1.2.3/out/extension
[2021-06-23 08:03:55.385] [exthost] [error] Error: Language client is not ready yet
	at TotvsLanguageClientA.sendRequest (c:\Users\miqueias.fernandes\.vscode\extensions\totvs.tds-vscode-1.2.3\node_modules\vscode-languageclient\lib\client.js:1789:19)
	at Object.sendValidationRequest (c:\Users\miqueias.fernandes\.vscode\extensions\totvs.tds-vscode-1.2.3\out\protocolMessages.js:151:10)
	at c:\Users\miqueias.fernandes\.vscode\extensions\totvs.tds-vscode-1.2.3\out\serversView.js:117:117
	at _executeContributedCommand (c:\Users\miqueias.fernandes\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:108091)
	at _.$executeContributedCommand (c:\Users\miqueias.fernandes\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:108529)
	at d._doInvokeHandler (c:\Users\miqueias.fernandes\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:12815)
	at d._invokeHandler (c:\Users\miqueias.fernandes\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:12507)
	at d._receiveRequest (c:\Users\miqueias.fernandes\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:11160)
	at d._receiveOneMessage (c:\Users\miqueias.fernandes\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:10155)
	at c:\Users\miqueias.fernandes\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:8064
	at l.fire (c:\Users\miqueias.fernandes\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1835)
	at E.fire (c:\Users\miqueias.fernandes\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15634)
	at c:\Users\miqueias.fernandes\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:29816
	at l.fire (c:\Users\miqueias.fernandes\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1835)
	at E.fire (c:\Users\miqueias.fernandes\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15634)
	at t._receiveMessage (c:\Users\miqueias.fernandes\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:20892)
	at c:\Users\miqueias.fernandes\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17778
	at l.fire (c:\Users\miqueias.fernandes\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1835)
	at c.acceptChunk (c:\Users\miqueias.fernandes\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12995)
	at c:\Users\miqueias.fernandes\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12343
	at Socket.b (c:\Users\miqueias.fernandes\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:13287)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) totvs-developer-studio.connect

**Comment by lwtnb-wrk** [comment]
@Miqueiasfer Poderia dar mais detalhes de como podemos reproduzir esse erro?
De qualquer forma veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by Miqueiasfer** [comment]
quando abro o vscode ja começa a aparecer o erro abaixo:

---------------------------v---------------------------------------------------
   //////  ////    //////  |  TOTVS Developer Studio for VS-Code
    //    //  //  //       |  Version 1.2.3
   //    //  //  //////    |  TOTVS Technology
  //    //  //      //     |
 //    ////    //////      |  https://github.com/totvs/tds-vscode
 --------------------------^---------------------------------------------------
[Info  - 10:59:38] Initializing Language Server.
[Error - 10:59:38] Server initialization failed.
  Message: Invalid rootUri. Please fix your workspace configuration and try 
again.

  Code: 3081 
[Error - 10:59:38] Starting client failed
  Message: Invalid rootUri. Please fix your workspace configuration and try again.
[totvsls.log](https://github.com/totvs/tds-vscode/files/6702403/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/6702404/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/6702405/totvsls_out.log)

  Code: 3081

**Comment by Miqueiasfer** [comment]
ontem estava funcionando normal, mas hoje quando fui abrir o VsCode para compilar deu este erro

**Comment by danielbolognani** [comment]
Bom dia @Miqueiasfer o seu workspace é uma pasta na rede (começando com \\) isso não é suportado na nossa extensão.
Utilize uma pasta local, ou ao menos, mapeie a pasta de rede para uma unidade local.

**Comment by Miqueiasfer** [comment]
eu utilizo uma unidade mapeada, inclusive funcionava normalmente ate ontem.

Minha unidade aqui está da seguinte forma:

Z:\protheus\my projects\VAMTEC

**Comment by danielbolognani** [comment]
Segundo o log, o VSCode tentou abrir o workspace em: \\27.27.1.3\mp12r25\protheus\my projects\VAMTEC
E deu erro na abertura

**Comment by Miqueiasfer** [comment]
carreguei a pasta novamente no vsCode e ai deu certo
